// Core engine and Unity dependencies used by the vehicle simulation.
﻿using System;
using UnityEngine;

// Serializable data model for drivetrain state and transmission behavior.
[Serializable]
public class Engine
{
    // Engine idle speed in revolutions per minute.
    public float idleRPM = 800f;
    // Maximum engine speed used to normalize power output and protect the drivetrain.
    public float maxRPM = 8500f;
    // Forward gear ratios, ordered from lowest to highest gear.
    public float[] gearRatios = { 3.31f, 2.27f, 1.69f, 1.32f, 1.02f, 0.82f, 0.67f, 0.56f, 0.46f };
    // Final drive multiplier applied between the gearbox and driven wheels.
    public float finalDriveRatio = 3.73f;
    // Zero-based internal gear index; exposed to gameplay as a one-based gear number.
    private int currentGear = 0;
    // Enables automatic gear selection when true.
    public bool automaticTransmission = true;
    // Prevents drivetrain calculations from immediately changing gear during a shift.
    private bool switchingGears = false;
    // Duration of the simulated gear-change event.
    private float gearChangeTime = 0.09f;
    // Cached engine speed used by the rest of the vehicle systems.
    private float rpm = 0f;

    // Converts wheel angular velocity into engine RPM and keeps the result within safe bounds.
    public void SetRPM(float avgWheelAngVel)
    {
        if (float.IsNaN(avgWheelAngVel) || float.IsInfinity(avgWheelAngVel)) avgWheelAngVel = 0f;
        float wheelRPM = (avgWheelAngVel * 60f) / (2f * Mathf.PI);
        float ratio = Math.Abs(gearRatios[currentGear] * finalDriveRatio);
        rpm = Mathf.Clamp(Mathf.Max(idleRPM, wheelRPM * ratio), idleRPM, maxRPM);
        if (float.IsNaN(rpm) || float.IsInfinity(rpm)) rpm = idleRPM;
    }

    // Returns a normalized engine power value for the current engine state.
    public float GetCurrentPower(MonoBehaviour ctx)
    {
        if (switchingGears) return 0.3f;
        return Mathf.Clamp01(rpm / maxRPM);
    }

    // Advances the transmission by one gear and starts the shift-state timer.
    public void UpGear(MonoBehaviour ctx)
    {
        if (currentGear < gearRatios.Length - 1 && !switchingGears)
        { currentGear++; switchingGears = true; ctx.StartCoroutine(ResetGear()); }
    }
    // Moves the transmission down one gear and starts the shift-state timer.
    public void DownGear(MonoBehaviour ctx)
    {
        if (currentGear > 0 && !switchingGears)
        { currentGear--; switchingGears = true; ctx.StartCoroutine(ResetGear()); }
    }
    // Clears the temporary shift state after the configured shift duration.
    private System.Collections.IEnumerator ResetGear()
    { yield return new WaitForSeconds(gearChangeTime); switchingGears = false; }

    // Evaluates automatic transmission thresholds and requests an appropriate gear change.
    public void checkGearSwitching(MonoBehaviour ctx, float throttle = 0f)
    {
        if (switchingGears) return;
        if (rpm > maxRPM * 0.95f && currentGear < gearRatios.Length - 1) UpGear(ctx);
        else if (rpm < maxRPM * 0.6f && currentGear > 0) DownGear(ctx);
    }

    // Publicly expose the current gear using human-readable numbering.
    public int getCurrentGear() => currentGear + 1;
    // Publicly expose the current engine RPM.
    public float getRPM() => rpm;
    // Publicly expose whether a gear shift is currently in progress.
    public bool isSwitchingGears() => switchingGears;
}

// Serializable per-wheel configuration and runtime state.
[Serializable]
public class WheelProperties
{
    // Runtime skid-trail references are hidden because they are generated by the controller.
    [HideInInspector] public TrailRenderer skidTrail;
    [HideInInspector] public GameObject skidTrailGameObject;

    // Wheel mount position relative to the vehicle body.
    public Vector3 localPosition;

    // Default tuning guidance for front and rear wheel grip.
    // Front wheels: turnAngle = 30, gripMultiplier = 1.3
    // Rear  wheels: turnAngle = 0,  gripMultiplier = 0.7
    // Steering angle assigned to this wheel.
    public float turnAngle = 0f;
    // Multiplier used by the lateral grip model for this wheel.
    public float gripMultiplier = 1.0f;

    // Maximum suspension travel measured from the wheel mount.
    public float suspensionLength = 0.3f;
    // Effective wheel mass used by the rotational inertia calculation.
    public float mass = 20f;
    // Wheel radius used by suspension, circumference, and rotational calculations.
    public float size = 0.35f;
    // Drive torque available at this wheel.
    public float engineTorque = 500f;
    // Braking strength applied to wheel angular velocity.
    public float brakeStrength = 8f;

    // Runtime suspension state used to estimate damping between physics steps.
    [HideInInspector] public float lastSuspensionLength = 0f;
    // Runtime flag indicating that this wheel has exceeded the lateral grip threshold.
    [HideInInspector] public bool slidding;
    // World-space direction and magnitude of the calculated wheel slip force.
    [HideInInspector] public Vector3 worldSlipDirection;
    // World-space direction of the suspension force for debugging/telemetry.
    [HideInInspector] public Vector3 suspensionForceDirection;
    // Current world-space position of the physical wheel/contact probe.
    [HideInInspector] public Vector3 wheelWorldPosition;
    // Cached wheel circumference used by wheel-related calculations.
    [HideInInspector] public float wheelCircumference;
    // Runtime drive torque after throttle and engine-power modulation.
    [HideInInspector] public float torque;
    // Visual wheel object instantiated at runtime.
    [HideInInspector] public GameObject wheelObject;
    // Wheel-local velocity used by the tire model.
    [HideInInspector] public Vector3 localVelocity;
    // Calculated normal load generated by the suspension.
    [HideInInspector] public float normalForce;
    // Runtime wheel angular velocity in radians per second.
    [HideInInspector] public float angularVelocity;
    // Normalized lateral slip value used by assists and skid logic.
    [HideInInspector] public float slip;
    // Smoothed per-wheel steering and throttle input.
    [HideInInspector] public Vector2 input = Vector2.zero;
    // Runtime brake amount applied to this wheel.
    [HideInInspector] public float brake;
    // Historical slip state used by traction-control behavior.
    [HideInInspector] public float slipHistory;
    // Amount of throttle reduction currently applied by traction control.
    [HideInInspector] public float tcsReduction;
}

// Main vehicle controller. It owns input, suspension, tire forces, drivetrain coupling, and wheel visuals.
public class CarController : MonoBehaviour
{
    // External references and serialized vehicle configuration.
    [Header("References")]
    public CarAudio audioController;
    public Engine e;
    public GameObject wheelPrefab;
    public GameObject skidMarkPrefab;
    public WheelProperties[] wheels;

    // Tire friction parameters. These define the available contact force before clamping.
    // ── Friction ─────────────────────────────────────────────────────────────
    // These are now public so you can tune in Inspector without recompiling
    [Header("Friction")]
    public float coefStaticFriction = 1.2f;
    public float coefKineticFriction = 0.85f;

    // Grip tuning is separated from the raw friction coefficients for fast handling iteration.
    // ── Grip ──────────────────────────────────────────────────────────────────
    // wheelGripX controls turning force.
    // IMPORTANT: this value is applied as an impulse multiplier, not Newtons.
    // Start with 30 and raise if car still slides sideways.
    [Header("Grip")]
    public float wheelGripX = 30f;   // lateral  — raise this to fix sliding
    public float wheelGripZ = 8f;    // longitudinal — lower = more wheelspin

    // Suspension force and damping configuration.
    // ── Suspension ────────────────────────────────────────────────────────────
    [Header("Suspension")]
    public float suspensionForce = 200f;
    public float suspensionForceClamp = 10000f;
    public float dampAmount = 5f;

    // Body-level dynamics tuning.
    // ── Body ──────────────────────────────────────────────────────────────────
    [Header("Body")]
    public float downforce = 0.05f;
    public Vector3 COMOffset = new Vector3(0f, -0.3f, 0.5f);
    public float Inertia = 1.2f;

    // Driver-assistance systems intended to stabilize the vehicle without replacing the physics model.
    // ── Assists ───────────────────────────────────────────────────────────────
    [Header("Assists")]
    public bool throttleAssist = true;
    public bool steeringAssist = true;
    [Range(0f, 0.5f)] public float steeringAssistStrength = 0.05f;

    // Runtime state deliberately hidden from the Inspector.
    // ── Runtime ───────────────────────────────────────────────────────────────
    [HideInInspector] public Rigidbody rb;
    [HideInInspector] public Vector2 userInput = Vector2.zero;
    [HideInInspector] public float isBraking = 0f;
    [HideInInspector] public bool forwards = true;

    // Input and recovery state that should persist across frames.
    private float handbrakeInput = 0f;
    private float lastResetTime = -10f;
    private const float resetCooldown = 2f;

    // Lifecycle and simulation entry points.
    // ─────────────────────────────────────────────────────────────────────────

    // Initialize the rigidbody and construct all runtime wheel and skid-mark objects.
    private void Start()
    {
        rb = GetComponent<Rigidbody>();
        if (!rb) rb = gameObject.AddComponent<Rigidbody>();

        // Keep the physics body deterministic from the controller side instead of relying on scene state.
        // Rigidbody settings — set these here so they're always correct
        // regardless of what the Inspector shows on the component
        rb.mass = 100f;
        rb.linearDamping = 0.05f;
        rb.angularDamping = 0.5f;

        // Shift the center of mass and scale inertia to influence stability and rotational response.
        rb.centerOfMass += COMOffset;
        rb.inertiaTensor *= Inertia;

        // Build the visual wheel hierarchy and cache values required by the physics loop.
        foreach (var w in wheels)
        {
            w.wheelObject = Instantiate(wheelPrefab, transform);
            w.wheelObject.transform.localPosition = w.localPosition;
            w.wheelObject.transform.eulerAngles = transform.eulerAngles;
            w.wheelObject.transform.localScale = 2f * new Vector3(w.size, w.size, w.size);
            w.wheelCircumference = 2f * Mathf.PI * w.size;

            // Seed suspension history so the first physics step does not create an artificial damping spike.
            // initialise so damping doesn't spike on frame 1
            w.lastSuspensionLength = w.size * 2f + w.suspensionLength;

            if (skidMarkPrefab != null)
            {
                w.skidTrailGameObject = Instantiate(skidMarkPrefab, w.wheelObject.transform);
                w.skidTrailGameObject.transform.localPosition = Vector3.zero;
                w.skidTrailGameObject.transform.localRotation = Quaternion.identity;
                w.skidTrailGameObject.transform.parent = null;
                w.skidTrail = w.skidTrailGameObject.GetComponent<TrailRenderer>();
                if (w.skidTrail != null) w.skidTrail.emitting = false;
            }
        }

        // Clear transient traction-control and slip history when the vehicle starts.
        foreach (var w in wheels) { w.tcsReduction = 0f; w.slipHistory = 0f; }
    }

    // A simple orientation test used by the recovery system.
    private bool IsFlipped() => Vector3.Dot(transform.up, Vector3.up) < 0.1f;

    // Process player input and non-physics vehicle state once per rendered frame.
    private void Update()
    {
        // Manual vehicle recovery is intentionally handled outside FixedUpdate because it is an input action.
        // Reset
        if (Input.GetKeyDown(KeyCode.R) && Time.time - lastResetTime > resetCooldown)
        {
            lastResetTime = Time.time;
            float yRot = transform.rotation.eulerAngles.y;
            transform.rotation = Quaternion.Euler(0f, yRot, 0f);
            if (Physics.Raycast(transform.position, Vector3.down, 3f) || IsFlipped())
                transform.position += Vector3.up * 2f;
            rb.linearVelocity = transform.forward * 2f;
            rb.angularVelocity = Vector3.zero;
        }

        // AI-controlled vehicles provide their own input path and should not read player controls.
        if (GetComponent<CarAIControl>() != null) return;

        // Read raw player controls before applying smoothing and speed-sensitive steering.
        float rawH = Input.GetAxisRaw("Horizontal");
        float rawV = Input.GetAxisRaw("Vertical");

        // Reduce steering sensitivity as speed increases to make high-speed input less abrupt.
        float speedFactor = 1f / (1f + rb.linearVelocity.magnitude / 28f);
        userInput.x = Mathf.Lerp(userInput.x, rawH * speedFactor, Time.deltaTime * 10f);
        userInput.y = Mathf.Lerp(userInput.y, rawV, Time.deltaTime * 10f);

        // Determine whether reverse input should be treated as braking while moving forward.
        bool movingFwd = rb.linearVelocity.magnitude > 0.5f && forwards;
        isBraking = (rawV < -0.1f && movingFwd) ? 1f : 0f;

        // Handbrake is an instantaneous driver input sampled for the current frame.
        handbrakeInput = Input.GetKey(KeyCode.Space) ? 1f : 0f;

        // Update every wheel from shared vehicle input while allowing each wheel to maintain its own state.
        for (int i = 0; i < wheels.Length; i++)
        {
            var w = wheels[i];
            // Guard runtime slip data before it participates in control calculations.
            if (!IsValid(w.slip)) w.slip = 0f;

            // Traction-control logic reduces throttle when the tire is spinning beyond the target slip region.
            if (throttleAssist)
            {
                const float ts = 0.85f, tol = 0.05f;
                if (w.slip > ts + tol)
                    w.tcsReduction = Mathf.Lerp(w.tcsReduction, 1f,
                        Mathf.Clamp01((w.slip - ts) * 2f) / 5f);
                else if (w.slip < ts - tol)
                    w.tcsReduction = Mathf.Lerp(w.tcsReduction, 0f, 0.6f * Time.deltaTime);
                w.tcsReduction = Mathf.Clamp01(w.tcsReduction);
            }

            // Brake demand is reduced while traction control is intervening.
            w.brake = isBraking * (1f - w.tcsReduction);

            // Smooth steering independently for each wheel.
            w.input.x = Mathf.Lerp(w.input.x, userInput.x, Time.deltaTime * 10f);
            // Convert raw slip into a safe normalized range for the steering assist.
            float s = Mathf.Clamp01(w.slip);
            if (s > 0.3f && s < 1.5f && steeringAssist)
                w.input.x = Mathf.Lerp(w.input.x, 0f, s * Time.deltaTime * steeringAssistStrength * 10f);

            // Apply traction-control throttle reduction before smoothing the wheel throttle input.
            float finalThrottle = userInput.y * (1f - w.tcsReduction);
            if (!IsValid(finalThrottle)) finalThrottle = 0f;
            w.input.y = Mathf.Lerp(w.input.y, finalThrottle, 0.95f * Time.deltaTime * 60f);
            if (!IsValid(w.input.y)) w.input.y = 0f;
        }

        // Manual transmission controls. Automatic logic below can also request shifts.
        if (Input.GetKeyDown(KeyCode.E)) e.UpGear(this);
        else if (Input.GetKeyDown(KeyCode.Q)) e.DownGear(this);
        // Feed current throttle into the automatic transmission decision layer.
        e.checkGearSwitching(this, Mathf.Max(0f, userInput.y));

        // Update audio from the same runtime values driving the vehicle simulation.
        if (audioController != null)
        {
            float avg = 0f;
            foreach (var w in wheels) avg += w.slip;
            avg /= wheels.Length;
            audioController.UpdateAudioValues(e.getRPM(), Mathf.Max(0f, userInput.y),
                rb.linearVelocity.magnitude, avg, e.isSwitchingGears());
        }
    }

    // Execute force, suspension, tire, and wheel-rotation simulation at the physics timestep.
    private void FixedUpdate()
    {
        // Aerodynamic downforce increases with vehicle speed and is applied along the body up-axis.
        rb.AddForce(-transform.up * rb.linearVelocity.magnitude * downforce);

        // Accumulate wheel angular velocity for drivetrain RPM estimation.
        float avgAngVel = 0f;

        // Each wheel independently evaluates steering, velocity, torque, contact, suspension, and tire forces.
        foreach (var w in wheels)
        {
            // Suspension ray length includes wheel diameter plus the configured suspension travel.
            float rayLen = w.size * 2f + w.suspensionLength;
            // Physical wheel transform is the reference frame for steering and tire-local velocity.
            Transform wheelObj = w.wheelObject.transform;
            // Child transform contains the visible wheel mesh and is rotated separately from the physical wheel.
            Transform wheelVisual = wheelObj.GetChild(0);

            // 1. Steering establishes the wheel coordinate frame used by the tire calculations below.
            // ── 1. Steer the wheel ───────────────────────────────────────────
            wheelObj.localRotation = Quaternion.Euler(0f, w.turnAngle * w.input.x, 0f);

            // 2. Tire velocity is evaluated in the steered wheel frame so lateral and longitudinal motion are separable.
            // ── 2. Measure velocity at this wheel in wheel-local space ────────
            // MUST happen AFTER rotation so local axes are correct
            // Calculate the wheel mount position in world space from the vehicle transform.
            w.wheelWorldPosition = transform.TransformPoint(w.localPosition);
            // Rigidbody point velocity includes both linear and angular body motion at this wheel location.
            Vector3 velAtWheel = rb.GetPointVelocity(w.wheelWorldPosition);
            // Convert the contact-point velocity into wheel-local coordinates.
            w.localVelocity = wheelObj.InverseTransformDirection(velAtWheel);
            // Track the vehicle travel direction from the wheel-local longitudinal velocity.
            forwards = w.localVelocity.z > 0.1f;

            // 3. Convert driver throttle and engine power into wheel drive torque.
            // ── 3. Engine torque ─────────────────────────────────────────────
            w.torque = w.engineTorque * w.input.y * e.GetCurrentPower(this);
            if (!IsValid(w.torque)) w.torque = 0f;

            // Approximate wheel rotational inertia as a solid cylinder.
            float inertia = w.mass * w.size * w.size / 2f;

            // 4. Cast from the wheel mount toward the ground to establish contact and suspension compression.
            // ── 4. Raycast ───────────────────────────────────────────────────
            RaycastHit hit;
            bool grounded = Physics.Raycast(w.wheelWorldPosition, -transform.up, out hit, rayLen);

            // 5. Lateral tire behavior is calculated from sideways velocity rather than relying solely on load.
            // ── 5. Lateral friction ──────────────────────────────────────────
            // This is the KEY fix for sliding.
            // We apply lateral friction as a direct velocity correction impulse
            // rather than a scaled force — this removes the normalForce dependency
            // that was making lateral grip near-zero at low speed.
            // Primary lateral velocity used by the grip model.
            float lateralVel = w.localVelocity.x;
            if (!IsValid(lateralVel)) lateralVel = 0f;

            // Additional contact-point velocity provides a second damping term when grounded.
            // Additional hit-point lateral damping (only when grounded)
            float lateralHitVel = 0f;
            if (grounded)
            {
                lateralHitVel = wheelObj.InverseTransformDirection(
                    rb.GetPointVelocity(hit.point)).x;
                if (!IsValid(lateralHitVel)) lateralHitVel = 0f;
            }

            // 6. Longitudinal friction attempts to match tire surface speed to ground speed.
            // ── 6. Longitudinal friction ─────────────────────────────────────
            float longitudinalFriction = -wheelGripZ *
                (w.localVelocity.z - w.angularVelocity * w.size);
            if (!IsValid(longitudinalFriction)) longitudinalFriction = 0f;

            // 7. Integrate wheel rotational velocity from drive torque and longitudinal tire resistance.
            // ── 7. Angular velocity ──────────────────────────────────────────
            // Torque balance produces the angular acceleration of the wheel.
            w.angularVelocity += (w.torque - longitudinalFriction * w.size)
                                / inertia * Time.fixedDeltaTime;
            // Brake torque damps wheel rotation over the current physics step.
            w.angularVelocity *= 1f - w.brake * w.brakeStrength * Time.fixedDeltaTime;
            if (!IsValid(w.angularVelocity)) w.angularVelocity = 0f;
            if (handbrakeInput > 0.5f) w.angularVelocity = 0f;

            // Ground contact enables suspension and tire-force generation.
            if (grounded)
            {
                // 8. Spring-damper suspension model converts compression into normal load.
                // ── 8. Suspension spring ─────────────────────────────────────
                // Suspension compression is the unused portion of the ray length.
                float compression = rayLen - hit.distance;
                // Estimate damping from the change in measured suspension distance.
                float damping = (w.lastSuspensionLength - hit.distance) * dampAmount;
                // Clamp suspension load to prevent unstable or non-physical force spikes.
                w.normalForce = Mathf.Clamp(
                    (compression + damping) * suspensionForce, 0f, suspensionForceClamp);
                if (!IsValid(w.normalForce)) w.normalForce = 0f;
                w.lastSuspensionLength = hit.distance;

                // Suspension force acts along the surface normal returned by the ground contact.
                Vector3 springForce = hit.normal * w.normalForce;
                w.suspensionForceDirection = springForce;

                // 9. Convert lateral velocity error into a direct lateral grip force, then enforce the tire force limit.
                // ── 9. LATERAL GRIP — applied directly as impulse ────────────
                // Instead of multiplying by normalForce (which breaks at low speed),
                // we cancel the sideways velocity directly each physics step.
                // gripMultiplier makes front wheels grip harder than rear.
                // Front/rear grip differences are represented by the per-wheel multiplier.
                float lateralFriction = -wheelGripX * w.gripMultiplier
                    * lateralVel - 2f * lateralHitVel;
                if (!IsValid(lateralFriction)) lateralFriction = 0f;

                // Static friction defines the maximum lateral force available at the current normal load.
                // Clamp lateral friction so it can't exceed what's physically possible
                float maxLateral = w.normalForce * coefStaticFriction;
                lateralFriction = Mathf.Clamp(lateralFriction, -maxLateral, maxLateral);

                // Longitudinal tire force is constrained by the same normal-load friction limit.
                // Longitudinal force also clamped by normal force
                float longForce = Mathf.Clamp(longitudinalFriction,
                    -w.normalForce * coefStaticFriction,
                     w.normalForce * coefStaticFriction);

                // Combine tire forces in the wheel frame before converting them to world space.
                Vector3 totalLocalForce = new Vector3(lateralFriction, 0f, longForce);
                Vector3 totalWorldForce = wheelObj.TransformDirection(totalLocalForce);
                // Cache the resulting world-space tire force for slip/skid visualization.
                w.worldSlipDirection = totalWorldForce;

                // Normalize actual lateral force against available lateral capacity for assist and skid decisions.
                w.slip = maxLateral > 0.001f
                    ? Mathf.Abs(lateralFriction) / maxLateral : 0f;
                w.slidding = w.slip > 1f;

                // Apply suspension and tire forces at the actual contact point so body translation and rotation respond naturally.
                // Apply spring + friction at contact point
                Vector3 totalForce = springForce + totalWorldForce;
                if (IsValid(totalForce.x) && IsValid(totalForce.y) && IsValid(totalForce.z))
                    rb.AddForceAtPosition(totalForce, hit.point);

                // Keep the visible wheel at the contact point plus its radius.
                // Wheel visual sits one radius above contact
                wheelObj.position = hit.point + transform.up * w.size;

                // 10. Generate or update skid marks when the tire exceeds the configured grip threshold.
                // ── 10. Skid marks ───────────────────────────────────────────
                HandleSkidMark(w, hit, wheelObj);
            }
            else
            {
                // When airborne, extend the wheel visually to the end of its suspension travel.
                // Airborne: hang wheel at full droop
                wheelObj.position = w.wheelWorldPosition - transform.up * (rayLen - w.size);
                StopSkidMark(w);
            }

            // Include this wheel in the average drivetrain speed estimate.
            avgAngVel += w.angularVelocity;
            // Rotate the visible wheel mesh from the simulated angular velocity.
            wheelVisual.Rotate(Vector3.right,
                w.angularVelocity * Mathf.Rad2Deg * Time.fixedDeltaTime, Space.Self);
        }

        // Average all wheel angular velocities before converting them to engine RPM.
        avgAngVel /= wheels.Length;
        e.SetRPM(avgAngVel);
    }

    // Small validation and presentation helpers kept outside the main physics loop.
    // ── Helpers ───────────────────────────────────────────────────────────────

    // Protect scalar physics calculations from NaN and Infinity propagation.
    private static bool IsValid(float f) => !float.IsNaN(f) && !float.IsInfinity(f);
    // Protect vector physics calculations from NaN and Infinity propagation.
    private static bool IsValid(Vector3 v) =>
        !float.IsNaN(v.x) && !float.IsNaN(v.y) && !float.IsNaN(v.z) &&
        !float.IsInfinity(v.x) && !float.IsInfinity(v.y) && !float.IsInfinity(v.z);

    // Owns the lifecycle of the wheel skid trail for a single wheel.
    private void HandleSkidMark(WheelProperties w, RaycastHit hit, Transform wheelObj)
    {
        // No slip means no active trail should remain on this wheel.
        if (!w.slidding) { StopSkidMark(w); return; }

        // Lazily create a trail if the wheel begins sliding after initialization.
        if (w.skidTrail == null && skidMarkPrefab != null)
        {
            GameObject obj = Instantiate(skidMarkPrefab, transform);
            obj.transform.SetParent(w.wheelObject.transform);
            obj.transform.localPosition = Vector3.zero;
            w.skidTrail = obj.GetComponent<TrailRenderer>();
            w.skidTrail.time = 30f;
            w.skidTrail.autodestruct = true;
            w.skidTrail.emitting = false;
            w.skidTrail.transform.position = hit.point;
            Vector3 sd = Vector3.ProjectOnPlane(w.worldSlipDirection.normalized, hit.normal);
            if (sd.sqrMagnitude < 0.001f)
                sd = Vector3.ProjectOnPlane(wheelObj.forward, hit.normal).normalized;
            w.skidTrail.transform.rotation =
                Quaternion.LookRotation(sd, hit.normal) * Quaternion.Euler(90f, 0f, 0f);
        }
        // Update an existing trail at the physical tire contact point.
        else if (w.skidTrail != null)
        {
            if (!w.skidTrail.emitting) w.skidTrail.emitting = true;
            w.skidTrail.transform.position = hit.point;
            Vector3 sd = Vector3.ProjectOnPlane(w.worldSlipDirection.normalized, hit.normal);
            if (sd.sqrMagnitude < 0.001f)
                sd = Vector3.ProjectOnPlane(wheelObj.forward, hit.normal).normalized;
            w.skidTrail.transform.rotation =
                Quaternion.LookRotation(sd, hit.normal) * Quaternion.Euler(90f, 0f, 0f);
        }
    }

    // Stop and clean up the active skid trail when the tire regains grip or leaves the ground.
    private void StopSkidMark(WheelProperties w)
    {
        // Nothing to clean up if this wheel has no active trail.
        if (w.skidTrail == null) return;
        // Detach an emitting trail so its existing segment can finish naturally before destruction.
        if (w.skidTrail.emitting)
        {
            w.skidTrail.emitting = false;
            w.skidTrail.transform.parent = null;
            Destroy(w.skidTrail.gameObject, w.skidTrail.time);
        }
        // Remove inactive trail objects immediately to avoid accumulating unused runtime objects.
        else Destroy(w.skidTrail.gameObject);
        w.skidTrail = null;
    }
}
