using UnityEngine;

/// <summary>
/// ScriptableObject that stores all configurable performance,
/// handling, and physics properties for a vehicle.
/// These values can be applied directly to a BMWCarController at runtime.
/// </summary>
[CreateAssetMenu(fileName = "NewCarData", menuName = "Racing/Car Data")]
public class CarDataSO : ScriptableObject
{
    [Header("Identity")]

    // Display name of the vehicle.
    public string carName;

    // Prefab associated with this vehicle configuration.
    public GameObject carPrefab;

    [Header("Mass & Dimensions")]

    // Total vehicle mass in kilograms.
    [Tooltip("Total car mass in kg")]
    public float mass = 800f;

    // Distance between the front and rear axles.
    [Tooltip("Distance between front and rear axles, in meters")]
    public float wheelbase = 2.9f;

    // Distribution of vehicle weight toward the right side.
    [Tooltip("Right-side weight bias, 0.5 = even, >0.5 = more weight on right (oval racing)")]
    [Range(0f, 1f)] public float rightSideMassRatio = 0.5f;

    [Header("Engine")]

    // Maximum engine horsepower.
    public float horsepower = 750f;

    // Maximum engine revolutions per minute.
    public float maxRPM = 9000f;

    // RPM at which peak torque is produced.
    public float peakTorqueRPM = 7000f;

    // Number of forward gears.
    public int gears = 6;

    [Header("Aerodynamics")]

    // Aerodynamic drag coefficient.
    [Tooltip("Drag coefficient (Cd)")]
    public float dragCoefficient = 0.35f;

    // Mechanical downforce generated by suspension geometry.
    [Tooltip("Downforce generated by mechanical grip (suspension geometry), in Newtons at reference speed")]
    public float mechanicalDownforce = 200f;

    // Aerodynamic downforce coefficient.
    [Tooltip("Aerodynamic downforce coefficient (Cl)")]
    public float aeroDownforceCoefficient = 1.2f;

    // Percentage of drag reduced while drafting.
    [Tooltip("Percentage drag reduction while drafting, 0-1")]
    [Range(0f, 1f)] public float draftingDragReduction = 0.3f;

    // Length of the drafting effect behind another vehicle.
    [Tooltip("Length of the effective drafting zone behind a car, in meters")]
    public float draftingZoneLength = 15f;

    [Header("Speed")]

    // Maximum speed on superspeedway tracks.
    public float topSpeedSuperSpeedway = 340f; // km/h or mph

    // Maximum speed on short tracks.
    public float topSpeedShortTrack = 260f;

    [Header("Suspension")]

    // Front-left suspension spring rate.
    public float frontSpringRateLeft = 800f;

    // Front-right suspension spring rate.
    public float frontSpringRateRight = 800f;

    // Rear-left suspension spring rate.
    public float rearSpringRateLeft = 700f;

    // Rear-right suspension spring rate.
    public float rearSpringRateRight = 700f;

    // Maximum suspension travel.
    [Tooltip("Total suspension travel, in meters")]
    public float suspensionTravel = 0.15f;

    // Suspension damper stiffness.
    public float damperStiffness = 4000f;

    [Header("Brakes")]

    // Brake torque relative to vehicle mass.
    [Tooltip("Brake torque relative to car mass")]
    public float brakeTorqueMass = 3500f;

    // Front-to-rear brake force distribution.
    [Tooltip("Front/rear brake bias, 0 = full rear, 1 = full front")]
    [Range(0f, 1f)] public float brakeBalance = 0.55f;

    // Rate at which brake temperature increases.
    [Tooltip("Rate at which brakes accumulate heat under hard braking")]
    public float brakeHeatBuildup = 1.0f;

    [Header("Tyres")]

    // Maximum tyre grip before slipping.
    [Tooltip("Peak (static) friction coefficient before the tyre breaks loose")]
    public float tyreFrictionPeak = 1.2f;

    // Tyre grip while sliding.
    [Tooltip("Sliding (kinetic) friction coefficient once the tyre is slipping")]
    public float tyreFrictionSlide = 0.85f;

    // Width of the tyre.
    public float tyreWidth = 0.3f;

    // Radius of the tyre.
    public float tyreRadius = 0.33f;

    // Slip ratio that produces maximum longitudinal grip.
    [Tooltip("Slip ratio at which longitudinal grip peaks (typically 0.1-0.2)")]
    public float optimalSlipRatio = 0.12f;

    // Slip angle that produces maximum lateral grip.
    [Tooltip("Slip angle (degrees) at which lateral grip peaks (typically 6-10)")]
    public float optimalSlipAngle = 8f;

    /// <summary>
    /// Applies the stored vehicle configuration to the specified car.
    /// Updates the Rigidbody mass and passes this data to the
    /// BMWCarController.
    /// </summary>
    /// <param name="carObject">The vehicle GameObject receiving the data.</param>
    public void ApplyToCar(GameObject carObject)
    {
        // Exit if no vehicle was supplied.
        if (carObject == null) return;

        // Apply the configured mass to the Rigidbody.
        Rigidbody rb = carObject.GetComponent<Rigidbody>();
        if (rb) rb.mass = mass;

        // Pass this ScriptableObject to the vehicle controller.
        BMWCarController controller = carObject.GetComponent<BMWCarController>();
        if (controller)
        {
            controller.SetCarData(this);
        }
    }
}